<?php

/**
 * @file
 * Contains scorm_cloud.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function scorm_cloud_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the scorm_cloud module.
    case 'help.page.scorm_cloud':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Scorm Cloud Intigration with Drupal') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function scorm_cloud_theme() {
  return [
    'scorm_cloud' => [
      'template' => 'scorm_cloud',
      'render element' => 'children',
    ],
  ];
}
